# Test file to check the reusable parser for the ENF Grant Framework application
# Ted Cahall 25May2022
#
# uses a sample file from the directory
#
name: Call a reusable parser

on:
  workflow_dispatch:

jobs:
  call-parser:
    uses: ./.github/workflows/reusable-parser.yml
    with:
      filename: "applications/oci-transaction-lifecycle.md"
    
  echo-the-returned-fields:
    runs-on: ubuntu-latest
    needs: call-parser
    steps:
      - id: echo1
        run: echo "project name ${{ needs.call-parser.outputs.project_name }} "
      - id: echo2
        run: echo "contact name ${{ needs.call-parser.outputs.contact_name }}"
      - id: echo3
        run: echo "team name ${{ needs.call-parser.outputs.team_name }}"
      - id: echo4
        run: echo "app_email ${{ needs.call-parser.outputs.app_email }}"
      - id: echo5
        run: echo "total cost ${{ needs.call-parser.outputs.total_cost }}"
